# Akbots - Don't Remove Credit - @AkBots_Official
#
# Auto-generated command index for /aiulta (the AI action agent).
#
# Built by a one-time static scan of every Akbots/*.py plugin file, looking
# for `@Client.on_message(filters.command([...]) ...)` handlers. Each entry
# records which module/function implements a command and whether it's
# admin-only / private-only / group-only, so aiulta.py can dispatch to it
# by name and enforce the exact same permission rules the command already
# has — aiulta never bypasses ADMINS-gating, it just gives the LLM a way to
# pick the right existing command instead of adding new capabilities.
#
# Intentionally excluded (never dispatchable via AI, even for admins):
# /eval, /shell, /sh, /checkdeps, /cfcheck, /cfdetect (devtools.py) — raw
# code/shell execution is never safe to put behind an LLM tool call, since
# a crafted instruction (or text the LLM is asked to summarize/forward)
# could trick the model into running something destructive.
#
# Regenerate after adding/removing plugin commands:
#   python3 build/gen_registry3.py   (see repo /build folder, dev-only)
# and re-paste the resulting COMMAND_REGISTRY list below.

COMMAND_REGISTRY = [
    {'commands': ['ban'], 'module': 'admin', 'function': 'ban', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['unban'], 'module': 'admin', 'function': 'unban', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['set_dump'], 'module': 'admin', 'function': 'set_dump', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['dblink'], 'module': 'admin', 'function': 'dblink', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['add_unsubscribe', 'del_unsubscribe'], 'module': 'admin', 'function': 'manage_force_subscribe', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['domains', 'sites', 'supported'], 'module': 'akbypass', 'function': 'domains_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['akstats', 'bypassstats'], 'module': 'akbypass', 'function': 'ak_stats_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['anime', 'subsplease'], 'module': 'anime', 'function': 'anime_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_anime_channel'], 'module': 'anime', 'function': 'set_anime_channel_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['del_anime_channel'], 'module': 'anime', 'function': 'del_anime_channel_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['anime_channel_status'], 'module': 'anime', 'function': 'anime_channel_status_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['watch'], 'module': 'anime_watcher', 'function': 'cmd_watch', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['unwatch'], 'module': 'anime_watcher', 'function': 'cmd_unwatch', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['watchlist'], 'module': 'anime_watcher', 'function': 'cmd_watchlist', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['watchtime'], 'module': 'anime_watcher', 'function': 'cmd_watchtime', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cleanup'], 'module': 'anime_watcher', 'function': 'cmd_cleanup', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['wthumb'], 'module': 'anime_watcher', 'function': 'cmd_wthumb', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': 'Per-anime-title thumbnail used when auto-uploading watched'},
    {'commands': ['wthumblist'], 'module': 'anime_watcher', 'function': 'cmd_wthumblist', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['wthumbdel'], 'module': 'anime_watcher', 'function': 'cmd_wthumbdel', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['aadmin'], 'module': 'anime_watcher', 'function': 'cmd_aadmin', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['radmin'], 'module': 'anime_watcher', 'function': 'cmd_radmin', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['wadmins'], 'module': 'anime_watcher', 'function': 'cmd_wadmins', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['myanime'], 'module': 'anime_watcher', 'function': 'cmd_myanime', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['myanimedel'], 'module': 'anime_watcher', 'function': 'cmd_myanimedel', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['myanimelist'], 'module': 'anime_watcher', 'function': 'cmd_myanimelist', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['monitor'], 'module': 'anime_watcher', 'function': 'cmd_monitor', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['stopmonitor'], 'module': 'anime_watcher', 'function': 'cmd_stopmonitor', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['animebatch'], 'module': 'anime_watcher', 'function': 'cmd_batch', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['qr'], 'module': 'anvi_toolkit', 'function': 'qr_handler', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['ip'], 'module': 'anvi_toolkit', 'function': 'ip_info', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['genpassword', 'genpw'], 'module': 'anvi_toolkit', 'function': 'gen_password', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['weather'], 'module': 'anvi_toolkit', 'function': 'weather', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['hashtag', 'hastag'], 'module': 'anvi_toolkit2', 'function': 'hashtag_gen', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['code'], 'module': 'anvi_toolkit2', 'function': 'hex_code', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['day'], 'module': 'anvi_toolkit2', 'function': 'day_of_week', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['whatsapp', 'wa'], 'module': 'anvi_toolkit2', 'function': 'whatsapp_link', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['bored'], 'module': 'anvi_toolkit2', 'function': 'bored', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['gn', 'goodnight'], 'module': 'anvi_toolkit2', 'function': 'goodnight', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['unzip'], 'module': 'archive', 'function': 'unzip_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipcreate'], 'module': 'archive', 'function': 'zip_create_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zip'], 'module': 'archive', 'function': 'zip_start_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipname'], 'module': 'archive', 'function': 'zip_name_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipformat'], 'module': 'archive', 'function': 'zip_format_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zippass'], 'module': 'archive', 'function': 'zip_pass_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipencryption'], 'module': 'archive', 'function': 'zip_encryption_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipfolder'], 'module': 'archive', 'function': 'zip_folder_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipfiles'], 'module': 'archive', 'function': 'zip_files_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zipcancel'], 'module': 'archive', 'function': 'zip_cancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['donezip'], 'module': 'archive', 'function': 'zip_done_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['ftp'], 'module': 'aria2_dl', 'function': 'ftp_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rpcadd'], 'module': 'aria2_rpc', 'function': 'rpcadd_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rpctasks'], 'module': 'aria2_rpc', 'function': 'rpctasks_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rpcinfo'], 'module': 'aria2_rpc', 'function': 'rpcinfo_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['extract_audio'], 'module': 'audio_extract', 'function': 'extract_audio_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['audio_select', 'audioselect'], 'module': 'audio_select', 'function': 'audio_select_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['audiocancel'], 'module': 'audio_select', 'function': 'audio_cancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['audioqueue'], 'module': 'audio_select', 'function': 'audio_queue_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['audio_defaults'], 'module': 'audio_select', 'function': 'audio_defaults_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['getid'], 'module': 'audio_select', 'function': 'get_id_cmd', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['amerge'], 'module': 'audiomerge', 'function': 'start_amerge', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['amergestatus'], 'module': 'audiomerge', 'function': 'amerge_status', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['amergecancel'], 'module': 'audiomerge', 'function': 'cancel_amerge', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['amergedone', 'done_amerge'], 'module': 'audiomerge', 'function': 'finish_amerge', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['atrim'], 'module': 'audiotrim', 'function': 'atrim_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['autotest'], 'module': 'autopost', 'function': 'autotest_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['addaudio'], 'module': 'avmerge', 'function': 'addaudio_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['backupdb'], 'module': 'backup', 'function': 'backupdb_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['stats'], 'module': 'botadmin', 'function': 'bot_stats', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['check'], 'module': 'botadmin', 'function': 'check_user_premium', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['freez'], 'module': 'botadmin', 'function': 'freez_expired_premium', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['mode'], 'module': 'botadmin', 'function': 'bot_mode_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['restart'], 'module': 'botadmin', 'function': 'restart_bot', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['logs'], 'module': 'botadmin', 'function': 'send_logs', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['ytstatus', 'potoken', 'cookies'], 'module': 'botadmin', 'function': 'ytdl_auth_status', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['set'], 'module': 'botadmin', 'function': 'set_bot_commands', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['admin_commands_list'], 'module': 'botadmin', 'function': 'admin_commands_list', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['broadcast'], 'module': 'broadcast', 'function': 'broadcast_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['acast'], 'module': 'broadcast', 'function': 'announcement_cast_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['users'], 'module': 'broadcast', 'function': 'users_count', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['bulk'], 'module': 'bulklinks', 'function': 'bulk_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['buzzupload'], 'module': 'buzzheavier_upload', 'function': 'buzzupload_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_caption'], 'module': 'caption', 'function': 'set_caption', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['see_caption'], 'module': 'caption', 'function': 'see_caption', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_caption'], 'module': 'caption', 'function': 'del_caption', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['catbox'], 'module': 'catbox', 'function': 'catbox_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['channels'], 'module': 'channels', 'function': 'channels_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addroute'], 'module': 'channels', 'function': 'addroute_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['delroute'], 'module': 'channels', 'function': 'delroute_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['chat'], 'module': 'chatbot', 'function': 'chat_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['compress'], 'module': 'compress', 'function': 'compress_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['tovideo'], 'module': 'convert', 'function': 'tovideo_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['todocument'], 'module': 'convert', 'function': 'todocument_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['tomp4'], 'module': 'convert', 'function': 'tomp4_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cookiecheck'], 'module': 'cookiecheck', 'function': 'cookiecheck_command', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setcookies'], 'module': 'cookies_manager', 'function': 'setcookies_command', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cookie'], 'module': 'cookies_manager', 'function': 'cookie_panel_command', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['listcookies'], 'module': 'cookies_manager', 'function': 'listcookies_command', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['delcookies', 'clearcookies'], 'module': 'cookies_manager', 'function': 'delcookies_command', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_channel_id', 'set_channel', 'add_channel_id'], 'module': 'customchannel', 'function': 'set_channel_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_channel_id'], 'module': 'customchannel', 'function': 'del_channel_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['channel_id', 'get_channel_id', 'channel_status'], 'module': 'customchannel', 'function': 'channel_status_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': 'Lists every channel/group the user currently has linked, or the'},
    {'commands': ['dailymotion'], 'module': 'dailymotion', 'function': 'dailymotion_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['deps'], 'module': 'dependency_manager', 'function': 'deps_cmd', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['install'], 'module': 'dependency_manager', 'function': 'install_cmd', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['dub'], 'module': 'dub', 'function': 'dub_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['dubpdf'], 'module': 'dub', 'function': 'dubpdf_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['encode'], 'module': 'encode', 'function': 'encode_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['encode_settings'], 'module': 'encode_settings', 'function': 'encode_settings_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fb'], 'module': 'facebook', 'function': 'fb_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fembed'], 'module': 'fembed', 'function': 'fembed_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['genlink'], 'module': 'filestore', 'function': 'genlink_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['batch'], 'module': 'filestore', 'function': 'batch_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['dbchannels'], 'module': 'filestore', 'function': 'list_db_channels', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['adddbchannel'], 'module': 'filestore', 'function': 'add_db_channel_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['deldbchannel'], 'module': 'filestore', 'function': 'del_db_channel_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['multidb'], 'module': 'filestore', 'function': 'toggle_multidb_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['autobatch'], 'module': 'filestore', 'function': 'autobatch_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['uploadmode'], 'module': 'filestore', 'function': 'uploadmode_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['autogenerate'], 'module': 'filestore', 'function': 'autogenerate_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['shortener'], 'module': 'filestore', 'function': 'shortener_cmd', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['link'], 'module': 'filetolink', 'function': 'link_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': '/link as a reply to a document/video/audio -> stream + download links'},
    {'commands': ['linkbatch'], 'module': 'filetolink_batch', 'function': 'linkbatch_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['filmyfly'], 'module': 'filmyfly', 'function': 'filmyfly_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['filmyfly'], 'module': 'filmyfly', 'function': 'filmyfly_auto_detect', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['filmyzilla'], 'module': 'filmyzilla', 'function': 'filmyzilla_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['filmyzillascan'], 'module': 'filmyzilla', 'function': 'filmyzilla_scan_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': '/filmyzillascan [max_categories] [max_movies_per_category]'},
    {'commands': ['setsource'], 'module': 'forward', 'function': 'setsource_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['settarget'], 'module': 'forward', 'function': 'settarget_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fwdstatus'], 'module': 'forward', 'function': 'fwdstatus_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fwdcancel'], 'module': 'forward', 'function': 'fwdcancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['reset'], 'module': 'forward', 'function': 'reset_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fwd_caption'], 'module': 'forward', 'function': 'fwd_caption_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fwd', 'forward'], 'module': 'forward', 'function': 'fwd_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fwdresume'], 'module': 'forward', 'function': 'fwdresume_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addsource'], 'module': 'forward_engine', 'function': 'addsource_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rmsource'], 'module': 'forward_engine', 'function': 'rmsource_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['sources'], 'module': 'forward_engine', 'function': 'sources_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addtarget'], 'module': 'forward_engine', 'function': 'addtarget_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rmtarget'], 'module': 'forward_engine', 'function': 'rmtarget_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['targets'], 'module': 'forward_engine', 'function': 'targets_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['forwardmode'], 'module': 'forward_engine', 'function': 'forwardmode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['forwardstatus'], 'module': 'forward_engine', 'function': 'forwardstatus_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addreplacer'], 'module': 'forward_engine', 'function': 'addreplacer_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['clearreplacer'], 'module': 'forward_engine', 'function': 'clearreplacer_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addremover'], 'module': 'forward_engine', 'function': 'addremover_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['clearremover'], 'module': 'forward_engine', 'function': 'clearremover_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setprefix'], 'module': 'forward_engine', 'function': 'setprefix_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setsuffix'], 'module': 'forward_engine', 'function': 'setsuffix_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['clearcaption'], 'module': 'forward_engine', 'function': 'clearcaption_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setbutton'], 'module': 'forward_engine', 'function': 'setbutton_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['delbutton'], 'module': 'forward_engine', 'function': 'delbutton_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setfilters'], 'module': 'forward_engine', 'function': 'setfilters_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['textonlymode'], 'module': 'forward_engine', 'function': 'textonlymode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': "Alias for the reference bot's 'Text Only Mode' — implemented as a"},
    {'commands': ['pimode'], 'module': 'forward_engine', 'function': 'pimode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': "The reference bot's 'Pi Mode' just unlocks selecting multiple"},
    {'commands': ['numbering'], 'module': 'forward_engine', 'function': 'numbering_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['bullets'], 'module': 'forward_engine', 'function': 'bullets_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['usernameremover'], 'module': 'forward_engine', 'function': 'usernameremover_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['linkremover'], 'module': 'forward_engine', 'function': 'linkremover_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['thetamode'], 'module': 'forward_engine', 'function': 'thetamode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['blastmode'], 'module': 'forward_engine', 'function': 'blastmode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['coursesellers'], 'module': 'forward_engine', 'function': 'coursesellers_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': 'One-click preset: strips links + deeplinks + usernames so buyers'},
    {'commands': ['deltamode'], 'module': 'forward_engine', 'function': 'deltamode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['akanager'], 'module': 'ftm_manager_menu', 'function': 'akanager_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['gallery'], 'module': 'gallery', 'function': 'gallery_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['gdrive'], 'module': 'gdrive', 'function': 'gdrive_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setgdrivetoken'], 'module': 'gdrive', 'function': 'setgdrivetoken_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['gemini', 'ai', 'ask'], 'module': 'gemini_chat', 'function': 'gemini_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['getemoji', 'emojiid'], 'module': 'getemoji', 'function': 'get_emoji_id_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['ghdl', 'hfdl'], 'module': 'ghrelease', 'function': 'ghhf_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addaccount'], 'module': 'github_accounts', 'function': 'add_account_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['accounts'], 'module': 'github_accounts', 'function': 'list_accounts_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['useaccount'], 'module': 'github_accounts', 'function': 'use_account_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['removeaccount'], 'module': 'github_accounts', 'function': 'remove_account_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['setgittoken'], 'module': 'github_accounts', 'function': 'set_git_token_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['tokens', 'tokenmanager'], 'module': 'github_accounts', 'function': 'token_manager_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['exportgh', 'exportsummary'], 'module': 'github_accounts', 'function': 'export_summary_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['create_repo'], 'module': 'github_tools', 'function': 'create_repo_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['delrepo'], 'module': 'github_tools', 'function': 'delete_repo_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['downloadrepo'], 'module': 'github_tools', 'function': 'download_repo_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['fork'], 'module': 'github_tools', 'function': 'fork_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['forkall'], 'module': 'github_tools', 'function': 'fork_all_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['add_collaborator'], 'module': 'github_tools', 'function': 'add_collaborator_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['remove_collaborator'], 'module': 'github_tools', 'function': 'remove_collaborator_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['gitprivate', 'gitpublic'], 'module': 'github_tools', 'function': 'change_repo_visibility_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['github', 'git'], 'module': 'github_tools', 'function': 'github_user_lookup_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['allrepo'], 'module': 'github_tools', 'function': 'all_repos_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['gofile'], 'module': 'gofile', 'function': 'gofile_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['groq', 'groqai'], 'module': 'groq_chat', 'function': 'groq_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['hdhub'], 'module': 'hdhub', 'function': 'hdhub_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['setherokutoken'], 'module': 'heroku_tools', 'function': 'set_heroku_token_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['createapp'], 'module': 'heroku_tools', 'function': 'create_app_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['addapp'], 'module': 'heroku_tools', 'function': 'add_collaboration_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['removeapp'], 'module': 'heroku_tools', 'function': 'remove_collaboration_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['herokulogs'], 'module': 'heroku_tools', 'function': 'heroku_logs_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['herokuinfo'], 'module': 'heroku_tools', 'function': 'heroku_info_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['delheroku'], 'module': 'heroku_tools', 'function': 'delete_heroku_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['veriable'], 'module': 'heroku_tools', 'function': 'heroku_variables_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['apps'], 'module': 'heroku_tools', 'function': 'heroku_apps_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['restartdynos'], 'module': 'heroku_tools', 'function': 'restart_dynos_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['rename'], 'module': 'heroku_tools', 'function': 'rename_app_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['history', 'downloads'], 'module': 'history_favs', 'function': 'history_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['favourites', 'favorites', 'favs'], 'module': 'history_favs', 'function': 'favourites_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['fav'], 'module': 'history_favs', 'function': 'fav_add_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['unfav'], 'module': 'history_favs', 'function': 'unfav_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['imgtolink', 'img2link', 'i2l'], 'module': 'imgtolink', 'function': 'imgtolink_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['imgurl'], 'module': 'imgtolink', 'function': 'imgurl_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cancel'], 'module': 'imgtolink', 'function': 'imgtolink_cancel', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['imgtolink', 'img2link', 'i2l', 'imgurl', 'cancel', 'start', 'help'], 'module': 'imgtolink', 'function': 'i2l_incoming_url', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['pfp', 'profilepic'], 'module': 'insta_extra', 'function': 'pfp_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['story', 'stories'], 'module': 'insta_extra', 'function': 'story_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['highlights', 'highlight'], 'module': 'insta_extra', 'function': 'highlights_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['insta', 'ig'], 'module': 'instagram', 'function': 'insta_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['jd'], 'module': 'jdownloader', 'function': 'jd_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['jdstatus'], 'module': 'jdownloader', 'function': 'jd_status_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['jiocinema'], 'module': 'jiocinema', 'function': 'jiocinema_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['saavn', 'jiosaavn'], 'module': 'jiosaavn', 'function': 'saavn_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['kuku'], 'module': 'kukutv', 'function': 'kuku_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['kukucancel'], 'module': 'kukutv', 'function': 'kuku_cancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['m3u8'], 'module': 'm3u8dl', 'function': 'm3u8_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['allcancel'], 'module': 'm3u8dl', 'function': 'allcancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['maintenance'], 'module': 'maintenance', 'function': 'maintenance_cmd', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['mf'], 'module': 'mediafire', 'function': 'mediafire_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mediainfo', 'minfo'], 'module': 'mediainfo', 'function': 'mediainfo_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['togif'], 'module': 'mediatools_extra', 'function': 'togif_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['audio8d'], 'module': 'mediatools_extra', 'function': 'audio8d_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['bassboost'], 'module': 'mediatools_extra', 'function': 'bassboost_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['trebleboost'], 'module': 'mediatools_extra', 'function': 'trebleboost_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['eq'], 'module': 'mediatools_extra', 'function': 'eq_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['slowreverb'], 'module': 'mediatools_extra', 'function': 'slowreverb_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['jsonformat'], 'module': 'mediatools_extra', 'function': 'jsonformat_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['subconvert'], 'module': 'mediatools_extra', 'function': 'subconvert_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mega'], 'module': 'mega', 'function': 'mega_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_metadata'], 'module': 'metadata', 'function': 'set_metadata_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['see_metadata'], 'module': 'metadata', 'function': 'see_metadata_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_metadata'], 'module': 'metadata', 'function': 'del_metadata_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['apply_metadata'], 'module': 'metadata', 'function': 'apply_metadata_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['deploy'], 'module': 'misc_tools', 'function': 'deploy_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['mongochk'], 'module': 'misc_tools', 'function': 'mongo_check_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['leavegroup'], 'module': 'misc_tools', 'function': 'leave_group_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['html'], 'module': 'misc_tools', 'function': 'html_download_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['pypi'], 'module': 'misc_tools', 'function': 'pypi_info_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['tgm', 'telegraph'], 'module': 'misc_tools', 'function': 'telegraph_upload_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['table'], 'module': 'misc_tools', 'function': 'multiplication_table_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['id'], 'module': 'misc_tools', 'function': 'id_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['movieinfo'], 'module': 'movieinfo', 'function': 'movieinfo_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['series'], 'module': 'movieinfo', 'function': 'series_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['imdb'], 'module': 'movieinfo', 'function': 'imdb_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': 'Quick info + poster, movie or TV — tries a movie match first, then'},
    {'commands': ['poster'], 'module': 'movieinfo', 'function': 'poster_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['setbot'], 'module': 'multibot', 'function': 'set_custom_bot', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rembot'], 'module': 'multibot', 'function': 'remove_custom_bot', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mute'], 'module': 'mute', 'function': 'mute_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mxplayer'], 'module': 'mxplayer', 'function': 'mxplayer_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['gpt', 'chatgpt'], 'module': 'openai_chat', 'function': 'gpt_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['imagine', 'image'], 'module': 'openai_chat', 'function': 'imagine_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['gptusage'], 'module': 'openai_chat', 'function': 'gpt_usage_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['gptstats'], 'module': 'openai_chat', 'function': 'gpt_stats_command', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['help_group_chat'], 'module': 'openai_chat', 'function': 'help_group_chat_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['pay'], 'module': 'pay', 'function': 'pay_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['pixeldrain', 'pd'], 'module': 'pixeldrain', 'function': 'pixeldrain_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['pocketfm'], 'module': 'pocketfm', 'function': 'pocketfm_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['myplan'], 'module': 'premium', 'function': 'my_plan', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['premium'], 'module': 'premium', 'function': 'premium_info', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['add_premium'], 'module': 'premium', 'function': 'add_premium_admin', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['remove_premium'], 'module': 'premium', 'function': 'remove_premium_admin', 'admin_only': True, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['transfer'], 'module': 'premium', 'function': 'transfer_premium', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['filepress', 'hubdrive'], 'module': 'premiumlinks', 'function': 'filepress_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['gdflix'], 'module': 'premiumlinks', 'function': 'gdflix_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['hubcloud'], 'module': 'premiumlinks', 'function': 'hubcloud_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['lksfy'], 'module': 'premiumlinks', 'function': 'lksfy_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setrcloneconf'], 'module': 'rclone_upload', 'function': 'setrcloneconf_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rclone'], 'module': 'rclone_upload', 'function': 'rclone_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rclonelist'], 'module': 'rclone_upload', 'function': 'rclonelist_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['referral'], 'module': 'referral', 'function': 'referral_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['referral_list'], 'module': 'referral', 'function': 'referral_list_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['autorename'], 'module': 'rename', 'function': 'set_autorename_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['see_autorename'], 'module': 'rename', 'function': 'see_autorename_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_autorename'], 'module': 'rename', 'function': 'del_autorename_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_prefix'], 'module': 'rename', 'function': 'set_prefix_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['see_prefix'], 'module': 'rename', 'function': 'see_prefix_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_prefix'], 'module': 'rename', 'function': 'del_prefix_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_suffix'], 'module': 'rename', 'function': 'set_suffix_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['see_suffix'], 'module': 'rename', 'function': 'see_suffix_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_suffix'], 'module': 'rename', 'function': 'del_suffix_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['uploadrepo'], 'module': 'repo_upload', 'function': 'upload_repo_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['release'], 'module': 'repo_upload', 'function': 'create_release_command', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['rss_add'], 'module': 'rss', 'function': 'rss_add_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rss_list'], 'module': 'rss', 'function': 'rss_list_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rss_remove'], 'module': 'rss', 'function': 'rss_remove_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rss_check'], 'module': 'rss', 'function': 'rss_check_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['sample'], 'module': 'sample_video', 'function': 'sample_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['autosample'], 'module': 'sample_video', 'function': 'autosample_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['screenshots'], 'module': 'screenshots', 'function': 'screenshots_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['autoscreenshots'], 'module': 'screenshots', 'function': 'autoscreenshots_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['login', 'fwd_login'], 'module': 'session', 'function': 'login_start', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['logout'], 'module': 'session', 'function': 'logout', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cancel', 'cancellogin'], 'module': 'session', 'function': 'login_handler', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_expiry'], 'module': 'set_expiry', 'function': 'set_expiry_cmd', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['settings'], 'module': 'settings', 'function': 'settings_menu', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['commands'], 'module': 'settings', 'function': 'direct_commands', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setchat'], 'module': 'settings', 'function': 'set_dump_chat', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['upload_mode'], 'module': 'settings', 'function': 'upload_mode_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['bypass', 'shortbypass'], 'module': 'shortener_bypass', 'function': 'bypass_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['speedtest', 'speed'], 'module': 'speedtest', 'function': 'speedtest_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['spoiler'], 'module': 'spoiler', 'function': 'spoiler_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['spotify'], 'module': 'spotify', 'function': 'spotify_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['start'], 'module': 'start', 'function': 'send_start', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['help'], 'module': 'start', 'function': 'send_help', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['plan'], 'module': 'start', 'function': 'send_plan', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['cancel', 'stop'], 'module': 'start', 'function': 'send_cancel', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['ping'], 'module': 'start', 'function': 'send_ping', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['status'], 'module': 'start', 'function': 'send_status', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['about'], 'module': 'start', 'function': 'send_about', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['warning'], 'module': 'start', 'function': 'send_warning', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['terms'], 'module': 'start', 'function': 'send_terms', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['settings'], 'module': 'start', 'function': 'send_settings', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['storageinfo', 'storage'], 'module': 'storageinfo', 'function': 'storage_info_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['stape'], 'module': 'streamtape', 'function': 'streamtape_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addsub'], 'module': 'submerge', 'function': 'addsub_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['edittag'], 'module': 'tageditor', 'function': 'edittag_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setart'], 'module': 'tageditor', 'function': 'setart_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['queue'], 'module': 'task_manager', 'function': 'queue_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cancel_all'], 'module': 'task_manager', 'function': 'cancel_all_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['terabox'], 'module': 'terabox', 'function': 'terabox_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': '/terabox <link> [password] — same as pasting the link directly, plus'},
    {'commands': ['terastream'], 'module': 'terabox', 'function': 'terastream_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': '/terastream <link> — returns the resolved direct/stream URL instead'},
    {'commands': ['set_thumb'], 'module': 'thumbnail', 'function': 'set_custom_thumbnail', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['view_thumb', 'see_thumb'], 'module': 'thumbnail', 'function': 'view_custom_thumbnail', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_thumb', 'delete_thumb'], 'module': 'thumbnail', 'function': 'delete_custom_thumbnail', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['thumb_mode'], 'module': 'thumbnail', 'function': 'thumbnail_status', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['change_thumb'], 'module': 'thumbnail', 'function': 'change_existing_thumbnail', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': 'Reply to an already-sent video/document with /change_thumb to swap'},
    {'commands': ['tiktok', 'tt'], 'module': 'tiktok', 'function': 'tiktok_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['titanium'], 'module': 'titanium', 'function': 'titanium_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cancel'], 'module': 'titanium', 'function': 'titanium_replace_cancel', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addbot', 'delbot', 'titanium', 'cancel'], 'module': 'titanium', 'function': 'titanium_replace_token_catch', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['addbot'], 'module': 'titanium', 'function': 'addbot_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['delbot'], 'module': 'titanium', 'function': 'delbot_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['token'], 'module': 'token_gate', 'function': 'token_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['torrent'], 'module': 'torrent', 'function': 'torrent_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['trim'], 'module': 'trim', 'function': 'trim_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['unequify'], 'module': 'unequify', 'function': 'unequify_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['unequifycancel'], 'module': 'unequify', 'function': 'unequify_cancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['uptime'], 'module': 'uptime_monitor', 'function': 'uptime_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['cancel'], 'module': 'uptime_monitor', 'function': 'ut_cancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['shorten'], 'module': 'urlshortener', 'function': 'shorten_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['url', 'direct'], 'module': 'urluploader', 'function': 'url_upload_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['myuses'], 'module': 'user_stats', 'function': 'my_uses', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['totaluses'], 'module': 'user_stats', 'function': 'total_uses', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['useruses'], 'module': 'user_stats', 'function': 'check_user_cmd', 'admin_only': True, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['mydb'], 'module': 'userdb', 'function': 'mydb_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_mydb'], 'module': 'userdb', 'function': 'set_mydb_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_mydb'], 'module': 'userdb', 'function': 'del_mydb_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['info', 'userinfo'], 'module': 'userinfo', 'function': 'info_cmd', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['merge'], 'module': 'videomerge', 'function': 'start_merge', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mergestatus'], 'module': 'videomerge', 'function': 'merge_status', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mergecancel'], 'module': 'videomerge', 'function': 'cancel_merge', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['mergedone', 'done_merge'], 'module': 'videomerge', 'function': 'finish_merge', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['splitvideo'], 'module': 'videosplitter', 'function': 'splitvideo_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['vk'], 'module': 'vk', 'function': 'vk_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['vc', 'gen'], 'module': 'voicechat', 'function': 'vc_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['vchelp'], 'module': 'voicechat', 'function': 'vchelp_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': ''},
    {'commands': ['set_watermark'], 'module': 'watermark', 'function': 'set_watermark_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['see_watermark'], 'module': 'watermark', 'function': 'see_watermark_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['del_watermark'], 'module': 'watermark', 'function': 'del_watermark_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['watermark_position'], 'module': 'watermark', 'function': 'watermark_position_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['apply_watermark'], 'module': 'watermark', 'function': 'apply_watermark_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_del_word'], 'module': 'words', 'function': 'set_del_word', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rem_del_word'], 'module': 'words', 'function': 'rem_del_word', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['set_repl_word'], 'module': 'words', 'function': 'set_repl_word', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['rem_repl_word'], 'module': 'words', 'function': 'rem_repl_word', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['ytraw', 'ytfallback'], 'module': 'youtube', 'function': 'youtube_fallback_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['setytoken'], 'module': 'youtube_upload', 'function': 'setytoken_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['ytupload'], 'module': 'youtube_upload', 'function': 'ytupload_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['yt', 'dl'], 'module': 'ytdl', 'function': 'yt_video_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['yta', 'song', 'adl'], 'module': 'ytdl', 'function': 'yt_audio_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['subtitle', 'subs', 'transcript'], 'module': 'ytdl', 'function': 'subtitle_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['search', 'yts'], 'module': 'ytsearch', 'function': 'search_command', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zee5'], 'module': 'zee5voot', 'function': 'zee5_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['voot'], 'module': 'zee5voot', 'function': 'voot_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zee5series'], 'module': 'zee5voot', 'function': 'zee5_series_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['zee5cancel'], 'module': 'zee5voot', 'function': 'zee5_series_cancel_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': ''},
    {'commands': ['arena', 'compare'], 'module': 'arena', 'function': 'arena_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': 'Run one prompt against two AI models side by side to compare answers.'},
    {'commands': ['arenamodels'], 'module': 'arena', 'function': 'arena_models_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': 'List model labels available for /arena.'},
    {'commands': ['coach'], 'module': 'coach', 'function': 'coach_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': 'Conversation-practice partner: casual chat, deep discussion, mock interview, or debate; remembers the session.'},
    {'commands': ['enhance', 'enhanceprompt'], 'module': 'enhance', 'function': 'enhance_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': 'Improve, rewrite, or enhance a rough prompt into a clearer, better, more effective one.'},
    {'commands': ['summarize', 'summarise'], 'module': 'summarizer', 'function': 'summarize_command', 'admin_only': False, 'private_only': False, 'group_only': False, 'description': 'Batch document analysis and long-form synthesis across multiple PDF/TXT/MD/DOCX/JSON files, exported as PDF too.'},
    {'commands': ['mastervideo', 'upscale', 'videomaster'], 'module': 'videoenhance', 'function': 'mastervideo_cmd', 'admin_only': False, 'private_only': True, 'group_only': False, 'description': 'Upscale/master a video to 1080p/2K/4K/8K with Lanczos scaling, 3D denoise, CAS sharpening, and HEVC 10-bit encode.'},
]

# command_name(lowercase) -> registry entry (first-match wins on rare
# collisions across plugins).
COMMAND_INDEX = {}
for _entry in COMMAND_REGISTRY:
    for _c in _entry["commands"]:
        COMMAND_INDEX.setdefault(_c, _entry)


def search_commands(query: str, limit: int = 10):
    """Very small keyword scorer over command names / module / function /
    description — good enough since command & module names in this codebase
    are already plain descriptive English words (terabox, ytdl, mediafire,
    broadcast, forward, rename, thumbnail, ...)."""
    q = (query or "").lower().strip()
    if not q:
        return []
    terms = [t for t in q.replace("/", " ").split() if t]
    scored = []
    for entry in COMMAND_REGISTRY:
        haystack = " ".join(entry["commands"] + [entry["module"], entry["function"], entry["description"]]).lower()
        score = 0
        for t in terms:
            if t in haystack:
                score += 2
            for c in entry["commands"]:
                if c.startswith(t) or t.startswith(c):
                    score += 3
        if score:
            scored.append((score, entry))
    scored.sort(key=lambda x: -x[0])
    out = []
    for _, entry in scored[:limit]:
        out.append({
            "command": entry["commands"][0],
            "aliases": entry["commands"][1:],
            "module": entry["module"],
            "admin_only": entry["admin_only"],
            "private_only": entry["private_only"],
            "group_only": entry["group_only"],
            "description": entry["description"],
        })
    return out
